apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: consumer-hpa
 # the namespace must be the same of the Deployment
 namespace: microservices
spec:
 scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # must match Deployment's .metadata/name
    name: consumer-dpl
 minReplicas: 1
 maxReplicas: 10
 metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10