apiVersion: "v1"
kind: "Service"
metadata:
  name: consumer-lb
  namespace: microservices
spec:
  selector:
    #matches deployment spec.template.labels
    #meaning the pods names
    app: transactions.consumer
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
