# to expose elasticsearch inside cluster
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  namespace: monitoring
  labels:
    service: elasticsearch-service
spec:
  type: ClusterIP
  selector:
    # match the .spec.template.metadata.labels
    app: elasticsearch
  ports:
  - port: 9200  #port this service listens
    targetPort: 9200 # the service redirects trafic to containerPort
    name: client
  - port: 9300
    targetPort: 9300
    name: nodes