
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: elasticsearch
   namespace: monitoring
   labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: elasticsearch
spec:
   serviceName: "elasticsearch"
   replicas: 1
   selector:
      matchLabels:
         app: elasticsearch
   template:
      metadata:
         labels:
            app: elasticsearch
      spec:
         containers:
            - name: elasticsearch-app
              image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
              imagePullPolicy: "IfNotPresent"
              resources:
                  requests: # minimum required
                     cpu: 300m
                     memory: "768Mi"
                  limits:   # maximum allowed
                     cpu: 300m
                     memory: "768Mi" 
              env:
                  - name: CLUSTER_NAME
                    value: elasticsearch-cluster
                  - name: NODE_NAME
                    value: elasticsearch-master
                  - name: "ES_JAVA_OPTS"
                    value: "-Xms256m -Xmx256m" 
                  - name: ELASTIC_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: elasticsearch-secrets
                        key: username
                  - name: ELASTIC_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: elasticsearch-secrets
                        key: password 
                  - name: KIBANA_SYSTEM
                    valueFrom:
                      secretKeyRef:
                        name: kibana-secrets
                        key: password                   
              ports:
                  - containerPort: 9200
                    name: client
                  - containerPort: 9300
                    name: nodes
              volumeMounts:
                  - name: elasticsearch-config
                    mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
                    readOnly: true
                    subPath: elasticsearch.yaml
                  - name: elasticsearch-pvc
                    mountPath: /usr/share/elasticsearch/data
         volumes:
           - name: elasticsearch-config
             configMap:
               name: elasticsearch-cm
         initContainers:
            # this is needed because minikube creates folder with root user ownership
            # and elasticsearch needs folder with owner with uid 1000
            - name: fix-permissions
              image: busybox
              command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
              securityContext:
                privileged: true
              volumeMounts:
              - name: elasticsearch-pvc
                mountPath: /usr/share/elasticsearch/data
   volumeClaimTemplates:
      - metadata:
          name: elasticsearch-pvc
          namespace: monitoring
        spec:
          storageClassName: ""
          volumeName: elasticsearch-pv
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 200Mi



