apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-cm
  namespace: monitoring
  labels:
    app: elasticsearch
data:
  elasticsearch.yaml: |
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.type: single-node
    network.host: 0.0.0.0

    # Disable features
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
    #xpack.security.autoconfiguration.enabled: false
    #xpack.security.enrollment.enabled: false