apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cm
  namespace: databases
data:
  createUser.js: |
    
    print('---> START <---');

    use transactions;
    var user = db.getUser(process.env.CONSUMER_USER);
    if(user == null){
      db.createUser(
          {
              user: process.env.CONSUMER_USER,
              pwd: process.env.CONSUMER_PASSWORD,
              roles: [
                  { role: "readWrite", db: "transactions" }
              ]
          }
      );
      print('User created');
    }else{
      print('User already exists');
    }
    print('---> END <---');
    