apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  claimRef: #pre-reserve for a specific pvc
    name: mongodb-pvc-mongodb-0
    namespace: databases
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongodb"