apiVersion: v1
kind: Secret
metadata:
  name: mongodb-consumer-secret
  namespace: databases
type: kubernetes.io/basic-auth
data:
  # consumerUser
  username: Y29uc3VtZXJVc2Vy
  # consumer123
  password: Y29uc3VtZXIxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-consumer-secret
  namespace: microservices
type: kubernetes.io/basic-auth
data:
  # consumerUser
  username: Y29uc3VtZXJVc2Vy
  # consumer123
  password: Y29uc3VtZXIxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-root-secrets
  namespace: databases
type: kubernetes.io/basic-auth
data:
  #root
  username: cm9vdAo=
  #mongo123
  password: bW9uZ28xMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secrets
  namespace: monitoring
type: kubernetes.io/basic-auth
data:
  #elastic
  username: ZWxhc3RpYw==
  #elastic123
  password: ZWxhc3RpYzEyMw==
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-secrets
  namespace: monitoring
type: kubernetes.io/basic-auth
data:
  password: a2liYW5hMTIz
