apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  claimRef: #pre-reserve for a specific pvc
    name: elasticsearch-pvc-elasticsearch-0
    namespace: monitoring
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elasticsearch"